language: php

php:
  - 5.6

sudo: false

services:
  - mysql

before_script:
  - mysql -e 'create database db_smartana;'
  - export DB_DATABASE=db-smartana
  - export DB_USERNAME=travis
  - export DB_PASSWORD=
  - cd api/
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --force
  - php artisan key:generate

script:
  - api/vendor/bin/phpunit
